### ISSUE TITLE
Wrong url value in ColonoscopyReport Months Until Next Colonoscopy

### ISSUE THREAD

**Issue by hammadirshad** [HL7Norway/Tarmkreftscreening#1]
**[ColonoscopyReport Months Until Next Colonoscopy](https://github.com/HL7Norway/Tarmkreftscreening/blob/main/Profiles/Extensions/MonthsUntilNextColonoscopy.StructureDefinition.xml)** have wrong url value [http://cancerregistration.no/fhir/StructureDefinition](cancerregistration.no/fhir/StructureDefinition) but other profiles have [http://kreftregisteret.no/fhir/StructureDefinition](kreftregisteret.no/fhir/StructureDefinition) url value in structure definition.

https://simplifier.net/NorwegianColonoscopyReport/MonthsUntilNextColonoscopy/~xml

 `<url value="http://cancerregistration.no/fhir/StructureDefinition/colonoscopyreport-monthsuntilnextcolonoscopy-extension" />`

**Comment by mmsmits** [comment]
Thanks! Fixed in new package
